<fix>(page): fix time format.

diff --git a/packages/nextjs/Dockerfile b/packages/nextjs/Dockerfile
--- a/packages/nextjs/Dockerfile
+++ b/packages/nextjs/Dockerfile
@@ -1,22 +1,45 @@
 # syntax=docker.io/docker/dockerfile:1
 
 FROM node:22-alpine AS base
+
+# Install dependencies only when needed
+FROM base AS deps
+# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
+RUN apk add --no-cache libc6-compat
+WORKDIR /app
+
+RUN corepack enable
+
+# Install dependencies based on the preferred package manager
+COPY package.json yarn.lock* ./
+
+RUN yarn config set npmRegistryServer https://registry.npmmirror.com
+RUN yarn config set nodeLinker node-modules
+RUN yarn install --network-timeout 100000
+RUN ls -al
+
+
 # Rebuild the source code only when needed
 FROM base AS builder
 WORKDIR /app
-
+COPY --from=deps /app/node_modules ./node_modules
 COPY . .
-RUN apk add --no-cache --upgrade libc6-compat bash
-RUN yarn config set npmRegistryServer https://registry.npmmirror.com
 
-RUN yarn --frozen-lockfile --network-timeout 100000
-RUN yarn next:build
+# Next.js collects completely anonymous telemetry data about general usage.
+# Learn more here: https://nextjs.org/telemetry
+# Uncomment the following line in case you want to disable telemetry during the build.
+# ENV NEXT_TELEMETRY_DISABLED=1
+
+RUN \
+  if [ -f yarn.lock ]; then yarn run next:build; \
+  else echo "Lockfile not found." && exit 1; \
+  fi
 
 # Production image, copy all the files and run next
 FROM base AS runner
 WORKDIR /app
 
-ENV NODE_ENV=development
+ENV NODE_ENV=production
 # Uncomment the following line in case you want to disable telemetry during runtime.
 # ENV NEXT_TELEMETRY_DISABLED=1
 
@@ -27,8 +50,8 @@ COPY --from=builder /app/packages/nextjs/public ./public
 
 # Automatically leverage output traces to reduce image size
 # https://nextjs.org/docs/advanced-features/output-file-tracing
-COPY --from=builder --chown=nextjs:nodejs /app/packages/nextjs/dist ./
-COPY --from=builder --chown=nextjs:nodejs /app/packages/nextjs/dist/static ./.next/static
+COPY --from=builder --chown=nextjs:nodejs /app/packages/nextjs/.next/standalone ./
+COPY --from=builder --chown=nextjs:nodejs /app/packages/nextjs/.next/static ./.next/static
 
 USER nextjs
 
